geek_code = input("Input geek code: ")

geek_code = geek_code.split()

flags = {
        "GB": "Geek of Business",
        "GC": "Geek of Classics",
        "GCA": "Geek of Commercial Arts",
        "GCM": "Geek of Computer Management",
        "GCS": "Geek of Computer Science",
        "GCC": "Geek of Communications",
        "GE": "Geek of Engineering",
        "GED": "Geek of Education",
        "GFA": "Geek of Fine Arts",
        "GG": "Geek of Government",
        "GH": "Geek of Humanities",
        "GIT": "Geek of Information Technology",
        "GJ": "Geek of Jurisprudence (Law)",
        "GLS": "Geek of Library Science",
        "GL": "Geek of Literature",
        "GMC": "Geek of Mass Communications",
        "GM": "Geek of Math",
        "GMD": "Geek of Medicine",
        "GMU": "Geek of Music",
        "GPA": "Geek of Performing Arts",
        "GP": "Geek of Philosophy",
        "GS": "Geek of Science (Physics, Chemistry, Biology, etc.)",
        "GSS": "Geek of Social Science (Psychology, Sociology, etc.)",
        "GTW": "Geek of Technical Writing",
        "GO": "Geek of Other. Some types of geeks deviate from the normal geek activities. This is encouraged as true geeks come from all walks of life.",
        "GU": "Geek of 'Undecided'. This is a popular vocation with incoming freshmen.",
        "G!": "Geek of no qualifications. A rather miserable existence, you would think.",
        "GAT": "Geek of All Trades. For those geeks that can do anything and everything. GAT usually precludes the use of other vocational descriptors.",
        "d++": "I tend to wear conservative dress such as a business suit or worse, a tie.",
        "d+": "Good leisure-wear. Slacks, button-shirt, etc. No jeans, tennis shoes, or t-shirts.",
        "d": "I dress a lot like those found in catalog ads. Bland, boring, without life or meaning.",
        "d-": "I\'m usually in jeans and a t-shirt.",
        "d--": "My t-shirts go a step further and have a trendy political message on them.",
        "d---": "Punk dresser, including, but not limited to, torn jeans and shirts, body piercings, and prominent tattoos.",
        "dx": "Cross Dresser",
        "d?": "I have no idea what I am wearing right now, let alone what I wore yesterday.",
        "!d": "No clothing. Quite a fashion statement, don't you think?",
        "dpu": "I wear the same clothes all the time, no matter the occasion, forgetting to do laundry between wearings.",
        "s+++": "I usually have to duck through doors.",
        "s++": "I'm a basketball candidate.",
        "s+": "I'm a little taller than most.",
        "s": "I'm a geek of average height.",
        "s-": "I look up to most people.",
        "s--": "I look up to damn near everybody.",
        "s---": "I take a phone book with me when I go out so I can see to eat dinner.",
        "+++": "I take up three movie seats.",
        "++": "I'm a linebacker candidate.",
        "+": "I'm a little rounder than most.",
        " ": "I'm a geek of average roundness.",
        "-": "Everyone tells me to gain a few pounds.",
        "--": "I tend to have to fight against a strong breeze.",
        "---": "My bones are poking through my skin.",
        "a+++": "60 and up",
        "a++": "50-59",
        "a+": "40-49",
        "a": "30-39",
        "a-": "25-29",
        "a--": "20-24",
        "a---": "15-19",
        "a----": "10-14",
        "a-----": "9 and under (Geek is training?)",
        "a?": "immortal",
        "!a": "it's none of your business how old I am",
        "C++++": "I'll be first in line to get the new cybernetic interface installed into my skull.",
        "C+++": "You mean there is life outside of Internet? You're shittin' me! I haven't dragged myself to class in weeks.",
        "C++": "Computers are a large part of my existence. When I get up in the morning, the first thing I do is log myself in. I play games or mud on weekends, but still manage to stay off of academic probation.",
        "C+": "Computers are fun and I enjoy using them. I play a mean game of DOOM! and can use a word processor without resorting to the manual too often. I know that a 3.5\" disk is not a hard disk. I also know that when it says 'press any key to continue', I don't have to look for a key labeled 'ANY'.",
        "C": "Computers are a tool, nothing more. I use it when it serves my purpose.",
        "C-": "Anything more complicated than my calculator and I'm screwed.",
        "C--": "Where's the on switch?",
        "C---": "If you even mention computers, I will rip your head off!",
        "B": "BSD",
        "L": "Linux",
        "U": "Ultrix",
        "A": "AIX",
        "V": "SysV",
        "H": "HPUX",
        "I": "IRIX",
        "O": "OSF/1",
        "S": "Sun OS/Solaris",
        "C": "SCO Unix",
        "X": "NeXT",
        "*": "Some other not listed",
        "U++++": "I am the sysadmin. If you try and crack my machine don't be surprised if the municipal works department gets an \"accidental\" computer-generated order to put start a new landfill on your front lawn or your quota is reduced to 4K.",
        "U+++": "I don't need to crack /etc/passwd because I just modified su so that it doesn't prompt me. The admin staff doesn't even know I'm here. If you don't understand what I just said, this category does NOT apply to you!",
        "U++": "I've get the entire admin ticked off at me because I am always using all of the CPU time and trying to run programs that I don't have access to. I'm going to try cracking /etc/passwd next week, just don't tell anyone.",
        "U+": "I not only have a Unix account, but I slam VMS any chance get.",
        "U": "I have a Unix account to do my stuff in",
        "U-": "I have a VMS account.",
        "U--": "I've seen Unix and didn't like it. DEC rules!",
        "U---": "Unix geeks are actually nerds in disguise.",
        "P+++++": "I am Larry Wall, Tom Christiansen, or Randal Schwartz.",
        "P++++": "I don't write Perl, I speak it. Perl has superseded all other programming languages. I firmly believe that all programs can be reduced to a Perl one-liner. I use Perl to achieve U+++ status.",
        "P+++": "Perl is a very powerful programming tool. Not only do I no longer write shell scripts, I also no longer use awk or sed. I use Perl for all programs of less than a thousand lines.",
        "P++": "Perl is a powerful programming tool. I don't write shell scripts anymore because I write them in Perl.",
        "P+": "I know of perl. I like perl. I just haven't learned much perl, but it is on my agenda.",
        "P": "I know Perl exists, but that's all.",
        "P-": "What's Perl got that awk and sed don't have?",
        "P--": "Perl users are sick, twisted programmers who are just showing off.",
        "P---": "Perl combines the power of sh, the clarity of sed, and the performance of awk with the simplicity of C. It should be banned.",
        "P?": "What's Perl?",
        "!P": "Our paranoid admin won't let us install Perl! Says it's a \"hacking tool\".",
        "L+++++": "I am Linus, grovel before me.",
        "L++++": "I am a Linux wizard. I munch C code for breakfast and have enough room left over for a kernel debugging. I have so many patches installed that I lost track about ten versions ago. Linux newbies consider me a net.god.",
        "L+++": "I use Linux exclusively on my system. I monitor comp.os.linux.* and even answer questions sometimes.",
        "L++": "I use Linux ALMOST exclusively on my system. I've given up trying to achieve Linux.God status, but welcome the OS as a replacement for DOS. I only boot to DOS to play games.",
        "L+": "I've managed to get Linux installed and even used it a few times. It seems like it is just another OS.",
        "L": "I know what Linux is, but that's about all",
        "L-": "I have no desire to use Linux and frankly don't give a rats patootie about it. There are other, better, operating systems out there. Like Mac, DOS, or Amiga-OS. Or, better yet even, would be another free Unix OS like FreeBSD.",
        "L--": "Unix sucks. Because Linux = Unix. Linux Sucks. I worship Bill Gates.",
        "L---": "I am Bill Gates.",
        "E+++": "Emacs is my login shell!! M-x doctor is my psychologist! I use emacs to control my TV and toaster oven! All you vi people don't know what you're missing! I read alt.relgion.emacs, alt.sex.emacs, and comp.os.emacs.",
        "E++": "I know and use elisp regularly!",
        "E+": "Emacs is great! I read my mail and news with it!",
        "E": "Yeah, I know what emacs is, and use it as my regular editor.",
        "E-": "Emacs is too big and bloated for my tastes",
        "E--": "Emacs is just a fancy word processor",
        "E---": "Emacs sucks! vi forever!!!",
        "E----": "Emacs sucks! pico forever!!!",
        "W+++": "I am a WebMaster. Don't even think about trying to view my homepage without the latest version of Netscape. When I'm not on my normal net connection, I surf the web using my Newton and a cellular modem.",
        "W++": "I have a homepage. I surf daily. My homepage is advertised in my .signature.",
        "W+": "I have the latest version of Netscape, and wander the web only when there's something specific I'm looking for.",
        "W": "I have a browser and a connection. Occasionally I'll use them.",
        "W-": "The web is really a pain. Life was so much easier when you could transfer information by simple ASCII. Now everyone won't even consider your ideas unless you spiff them up with bandwidth-consuming pictures and pointless information links.",
        "W--": "A pox on the Web! It wastes time and bandwidth and just gives the uneducated morons a reason to clutter the Internet.",
        "N++++": "I am Tim Pierce",
        "N+++": "I read so many news groups that the next batch of news comes in before I finish reading the last batch, and I have to read for about 2 hours straight before I'm caught up on the morning's news. Then there's the afternoon...",
        "N++": "I read all the news in a select handful of groups.",
        "N+": "I read news recreationally when I have some time to kill.",
        "N": "Usenet News? Sure, I read that once",
        "N-": "News is a waste of my time and I avoid it completely",
        "N--": "News sucks! 'Nuff said.",
        "N---": "I work for Time Magazine.",
        "N----": "I am a Scientologist.",
        "N*": "All I do is read news",
        "o+++++": "I am Steve Kinzler",
        "o++++": "I am an active Priest.",
        "o+++": "I was a Priest, but have retired.",
        "o++": "I have made the Best Of Oracularities.",
        "o+": "I have been incarnated at least once.",
        "o": "I've submitted a question, but it has never been incarnated.",
        "o-": "I sent my question to the wrong group and got flamed.",
        "o--": "Who needs answers from a bunch of geeks anyhow?",
        "K++++++": "I am Kibo",
        "K+++++": "I've had sex with Kibo",
        "K++++": "I've met Kibo",
        "K+++": "I've gotten mail from Kibo",
        "K++": "I've read Kibo",
        "K+": "I like Kibo",
        "K-": "I don't know who Kibo is",
        "K--": "I dislike Kibo",
        "K---": "I am currently hunting Kibo down with the intent of ripping his still-beating heart out of his chest and showing it to him as he dies",
        "K----": "I am Xibo",
        "w+++++": "I am Bill Gates",
        "w++++": "I have Windows, Windows 95, Windows NT, and Windows NT Advanced Server all running on my SMP RISC machine. I haven't seen daylight in six months.",
        "w+++": "I am a MS Windows programming god. I wrote a VxD driver to allow MS Windows and DOS to share the use of my waffle iron. P.S. Unix sux.",
        "w++": "I write MS Windows programs in C and think about using C++ someday. I've written at least one DLL.",
        "w+": "I have installed my own custom sounds, wallpaper, and screen savers so my PC walks and talks like a fun house. Oh yeah, I have a hundred TrueType(tm) fonts that I've installed but never used. I never lose Minesweeper and Solitaire",
        "w": "Ok, so I use MS Windows, I don't have to like it.",
        "w-": "I'm still trying to install MS Windows and have at least one peripheral that never works right",
        "w--": "MS Windows is a joke operating system. Hell, it's not even an operating system. NT is Not Tough enough for me either. 95 is how may times it will crash an hour.",
        "w---": "Windows has set back the computing industry by at least 10 years. Bill Gates should be drawn, quartered, hung, shot, poisoned, disembowelled, and then REALLY hurt.",
        "O+++": "I live, eat and breathe OS/2. All of my hard drives are HPFS. I am the Anti-Gates.",
        "O++": "I use OS/2 for all my computing needs. I use some DOS and Windows programs, but rune them under OS/2. If the program won't run under OS/2, then obviously I don't need it.",
        "O+": "I keep a DOS partition on my hard drive \"just in case\". I'm afraid to try HPFS.",
        "O": "I finally managed to get OS/2 installed but wasn't too terribly impressed.",
        "O-": "Tried it, didn't like it.",
        "O--": "I can't even get the thing to install!",
        "O---": "Windows RULES!!! Long live Bill Gates. (See w++++)",
        "O----": "I am Bill Gates of Borg. OS/2 is irrelevant.",
        "M++": "I am a Mac guru. Anything those dos putzes and unix nerds can do, I can do better, and if not, I'll write the damn software to do it.",
        "M+": "A Mac has it's uses and I use it quite often.",
        "M": "I use a Mac, but I'm pretty indifferent about it.",
        "M-": "Macs suck. All real geeks have a character prompt.",
        "M--": "Macs do more than suck. They make a user stupid by allowing them to use the system without knowing what they are doing. Mac weenies have lower IQs than the fuzz in my navel.",
        "V+++": "I am a VMS sysadmin. I wield far more power than those UNIX admins, because UNIX can be found on any dweeb's desktop. Power through obscurity is my motto.",
        "V++": "Unix is a passing fad compared to the real power in the universe, my VMS system.",
        "V+": "I tend to like VMS better than Unix",
        "V": "I've used VMS.",
        "V-": "Unix is much better than VMS for my computing needs.",
        "V--": "I would rather smash my head repeatedly into a brick wall than suffer the agony of working with VMS. It's reminiscent of a dead and decaying pile of moose droppings. Unix rules the universe.",
        "PS+++": "Legalize drugs! Abolish the government. \"Fuck the draft!\"",
        "PS++": "I give to liberal causes. I march for gay rights. I'm a card carrying member of the ACLU. Keep abortion safe and legal.",
        "PS+": "My whole concept of liberalism is that nobody has the right to tell anybody else what to do, on either side of the political fence. If you don't like it, turn the bloody channel.",
        "PS": "I really don't have an opinion; nobody's messing with my freedoms right now.",
        "PS-": "Label records! Keep dirty stuff off the TV and the Internet.",
        "PS--": "Oppose sex education, abortion rights, gay rights. Rush Limbaugh is my spokesman.",
        "PS---": "Repent left-wing sinners and change your wicked evil ways. Buchanan/Robertson in '96.",
        "PE+++": "Abolish antitrust legislation. Raise taxes on everyone but the rich so that the money can trickle-down to the masses. ",
        "PE++": "Keep the government off the backs of businesses. Deregulate as much as possible.",
        "PE+": "Balance the budget with spending cuts and an amendment.",
        "PE": "Distrust both government and business.",
        "PE-": "It's ok to increase government spending, so we can help more poor people. Tax the rich! Cut the defense budget!",
        "PE--": "Capitalism is evil! Government should provide the services we really need. Nobody should be rich.",
        "Y+++": "I am T.C. May",
        "Y++": "I am on the cypherpunks mailing list and active around Usenet. I never miss an opportunity to talk about the evils of Clipper and ITAR and the NSA. Orwell's 1984 is more than a story, it is a warning to our's and future generations. I'm a member of the EFF.",
        "Y+": "I have an interest and concern in privacy issues, but in reality I am not really all that active or vocal.",
        "Y": "I'm pretty indifferent on the whole issue.",
        "Y-": "It seems to me that all of these concerns are a little extreme. I mean, the government must be able to protect itself from criminals and the populace from indecent speech.",
        "Y--": "Get a life. The only people that need this kind of protection are people with something to hide. I think cypherpunks are just a little paranoid.",
        "Y---": "I am L. Detweiler.",
        "PGP++++": "I am Philip Zimmerman",
        "PGP+++": "I don't send or answer mail that is not encrypted, or at the very least signed. If you are reading this without decrypting it first, something is wrong. IT DIDN'T COME FROM ME!",
        "PGP++": "I have the most recent version and use it regularly",
        "PGP+": "\"Finger me for my public key\"",
        "PGP": "I\'ve used it, but stopped long ago.",
        "PGP-": "I don\'t have anything to hide.",
        "PGP--": "I feel that the glory of the Internet is in the anarchic, trusting environment that so nurtures the exchange of information. Encryption just bogs that down.",
        "PGP---": "If you support encryption on the Internet, you must be a drug dealer or terrorist or something like that.",
        "PGP----": "Oh, here is something you all can use that is better (insert clipper here).",
        "t+++": "It's not just a TV show, it's a religion. I know all about warp field dynamics and the principles behind the transporter. I have memorized the TECH manual. I speak Klingon. I go to cons with Vulcan ears on. I have no life.",
        "t++": "It's the best show around. I have all the episodes and the movies on tape and can quote entire scenes verbatim. I've built a few of the model kits too. But you'll never catch me at one of those conventions. Those people are kooks.",
        "t+": "It's a damn fine TV show and is one of the only things good on television any more.",
        "t": "It's just another TV show",
        "t-": "Maybe it is just me, but I have no idea what the big deal with Star Trek is. Perhaps I'm missing something but I just think it is bad drama.",
        "t--": "Star Trek is just another Space Opera. William Shatner isn't an actor, he's a poser! And what's with this Jean-Luc Picard? A Frenchman with a British accent? Come on. I'd only watch this show if my remote control broke. Isn't Voyager just a rehash of Lost in Space? Has Sisko even breathed in the last two seasons?",
        "t---": "Star Trek SUCKS! It is the worst crap I have ever seen! Hey, all you trekkies out there, GET A LIFE! (William Shatner is a t---)",
        "t*": "Star Trek SUCKS! It is the worst crap I have ever seen! Hey, all you trekkies out there, GET A LIFE! (William Shatner is a t---)",
        "5++++": "I am J. Michael Straczynski",
        "5+++": "I am a True Worshipper of the Church of Joe who lives eats breathes and thinks Babylon 5, and has Evil thoughts about stealing Joe's videotape archives just to see episodes earlier. I am planning to break into the bank and steal the triple-encoded synopsis of the 5-year arc.",
        "5++": "Finally a show that shows what a real future would look like. None of this Picardian \"Let's talk about it and be friends\" crap. And what's this? We finally get to see a bathroom! Over on that Enterprise, they've been holding it for over seven years!",
        "5+": "Babylon 5 certainly presents a fresh perspective in the Sci-Fi universe. I watch it weekly.",
        "5": "I've seen it, I am pretty indifferent to it.",
        "5-": "This show is sub-par. The acting is wooden, the special effects are obviously poor quality. In general, it seems like a very cheap Star Trek ripoff.",
        "5--": "You call this Sci-Fi? That is such a load of crap! This show is just a soap with bad actors, piss-poor effects, and lame storylines. Puh-leese."
        }

dec = []
for i in geek_code:
    if len(i.split("/")) == 1:
        dec.append(flags[i])
    else:
        for j in i.split("/"):
            if j.startswith("G"):
                dec.append(flags[j])
            else:
                dec.append(flags["G"+j])


print(";".join(dec))

